=== 1st-Chertsey-Scout-Group/runnymedescouts.org.uk/.astro/collections/groups.schema.json
{
  "$ref": "#/definitions/groups",
  "definitions": {
    "groups": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "mapLink": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "facebook": {
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "contact": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "location",
        "mapLink",
        "image"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== 1st-Chertsey-Scout-Group/runnymedescouts.org.uk/src/content/groups/chertsey-1st/index.json
{
    "name": "1st Chertsey",
    "location": "Staines Ln, KT16 8PS",
    "mapLink": "https://maps.app.goo.gl/buqViwWCRUkCaze7A",
    "image": "./Image.png",
    "contact":"https://1stchertseyscoutgroup.com/get-in-touch/",
    "facebook":"https://www.facebook.com/1stchertseyscoutgroup",
    "website": "https://1stchertseyscoutgroup.com/"
}

=== 1st-Chertsey-Scout-Group/runnymedescouts.org.uk/src/content/groups/addlestone-1st-4th/index.json
{
    "name": "1st/4th Addlestone",
    "location": "Spinney Hill, KT15 1AD",
    "mapLink": "https://maps.app.goo.gl/LF539JkFheDHnL6N6",
    "image": "./Image.png",
    "contact":"http://www.1st4th.org.uk/#contact-form-block-template-canvas",
    "facebook":"",
    "website": "http://www.1st4th.org.uk/"
}
